### ISSUE TITLE
Remove print statement in setOpacity

### ISSUE THREAD

**Issue by Nolence** [Furkankyl/full_screen_image#1]
Hi,

Very cool package! Can we possibly remove the debug [print statement here](https://github.com/Furkankyl/full_screen_image/blob/9ecc6ee85d95cc81d48f9f43f2ba99af6db0c3a0/lib/full_screen_image.dart#L109)?

**Comment by Furkankyl** [comment]
Hello,
Thanks for the warning, I'm deleting.
